on:
  pull_request:
    types: [opened, reopened]

jobs:
  collaborators-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
